[package]
name = "systeroid-core"
version = "0.1.0"
authors = ["Orhun ParmaksÄ±z <orhunparmaksiz@gmail.com>"]
repository = "https://github.com/orhun/systeroid"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
sysctl = "0.4.3"
thiserror = "1.0.29"
lazy_static = "1.4.0"
rayon = "1.5.1"
colored = "2.0.0"
serde = { version = "1.0.135", features = ["derive"] }
serde_json = "1.0.78"
dirs-next = "2.0.0"

[dependencies.parseit]
version = "0.1.0"
path = "../parseit"
features = ["gzip"]
