[package]
name = "systeroid-core"
version = "0.1.1" # managed by release.sh
description = "Core library of systeroid"
authors = ["Orhun ParmaksÄ±z <orhunparmaksiz@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
homepage = "https://github.com/orhun/systeroid"
repository = "https://github.com/orhun/systeroid"
keywords = ["linux", "kernel", "parameter", "sysctl"]
edition = "2021"
rust-version = "1.56.1"

[dependencies]
sysctl = "0.4.4"
thiserror = "1.0.32"
lazy_static = "1.4.0"
rayon = "1.5.3"
colored = "2.0.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
dirs-next = "2.0.0"
parseit = { version = "0.1.0", features = ["gzip"] }
rust-ini = "0.18.0"
dirs = "4.0.0"
