[package]
name = "systeroid-core"
version = "0.4.2" # managed by release.sh
description = "Core library of systeroid"
authors = ["Orhun ParmaksÄ±z <orhunparmaksiz@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
homepage = "https://github.com/orhun/systeroid"
repository = "https://github.com/orhun/systeroid"
keywords = ["linux", "kernel", "parameter", "sysctl"]
edition = "2021"
rust-version = "1.64.0"

[dependencies]
parseit.workspace = true
log.workspace = true
sysctl = "0.5.4"
thiserror = "1.0.44"
lazy_static = "1.4.0"
rayon = "1.7.0"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"
dirs-next = "2.0.0"
rust-ini = "0.19.0"
